apiVersion: v1
kind: Service
metadata:
  name: license-generator-service
  labels:
    app: license-generator
spec:
  type: NodePort
  selector:
      app: license-generator
  ports:
  - protocol : TCP
    nodePort: 30500
    port: 80
    targetPort: 80